# Generated by Django 5.2.6 on 2025-10-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day16app', '0002_alter_userinfo_account_alter_userinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('price', models.IntegerField(default=3000, verbose_name='价钱')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=1, verbose_name='靓号等级')),
                ('status', models.SmallIntegerField(choices=[(0, '未占用'), (1, '已使用')], default=0, verbose_name='状态')),
            ],
        ),
    ]
