# Generated by Django 5.2.6 on 2025-10-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
