# Generated by Django 5.2.6 on 2025-10-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0003_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
