# Generated by Django 5.2.6 on 2025-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0004_remove_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
