# Generated by Django 5.2.6 on 2025-10-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0005_userinfo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
