# Generated by Django 5.2.6 on 2025-10-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0006_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
