# Generated by Django 5.2.6 on 2025-10-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySiteApp', '0007_userinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
