# Generated by Django 5.2.6 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day16app', '0003_prettynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密  码')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynumber',
            name='price',
            field=models.IntegerField(default=2000, verbose_name='价钱'),
        ),
    ]
