# Generated by Django 5.2.6 on 2025-10-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day16app', '0004_admin_alter_prettynumber_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=1, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='任务详情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day16app.admin', verbose_name='负责人')),
            ],
        ),
    ]
