# Generated by Django 5.2.6 on 2025-10-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day16app', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '已付款'), (2, '待付款')], default=2, verbose_name='订单状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day16app.admin', verbose_name='管理员')),
            ],
        ),
    ]
